<a href="https://colab.research.google.com/github/snagine/PythonDSA/blob/main/Numpy_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: Numpy practice

import numpy as np

# Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)

# Print the matrix
print(matrix)

# Print the shape of the matrix
print(matrix.shape)

# Access the element at row 1, column 2
print(matrix[1, 2])

# Access the second row
print(matrix[1, :])

# Access the third column
print(matrix[:, 2])

# Add two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(matrix1 + matrix2)

# Multiply two matrices
print(matrix1 @ matrix2)

# Calculate the determinant of a matrix
matrix3 = np.array([[1, 2], [3, 4]])
print(np.linalg.det(matrix3))

# Calculate the inverse of a matrix
print(np.linalg.inv(matrix3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
5
[3 4 5]
[2 5 8]
[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np

a = np.array([[1,2,3], [2,3,4], [3,4,5]])
a[:,2] = [6,7,8]
print(a[:,2])
print(a)


[6 7 8]
[[1 2 6]
 [2 3 7]
 [3 4 8]]


In [ ]:
b = np.arange(9).reshape(3,3)
print(b)
# print(b.shape)
# print(b[:1]) # print 2nd column with all the rows
# print(b[:]) # print whole matrix
# print(b[1:]) # print 2nd row onwards with all the column elements [[3,4,5],[6,78]]
# print(b[1,:])# print 2nd row onwards with all the column elements [3,4,5]

print(b[1::2,::2]) # print 3,5 , logic: start from 1st row, skip 2nd element, start from 0th till end skip 2nd element

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 5]]
